[package]
name = "ru-ip-dump"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.12.23", default-features = false, features = ["rustls-tls", "http2"] }
flate2 = { version = "1.1.2", default-features = false, features = ["rust_backend"] }
